build:
  image: microsoft/aspnet:1.0.0-rc1-update1-coreclr
  commands:
    - ls
    - ls $DNX_USER_HOME
    - ls /opt
    - which dnx
    - which dnu
    - dnu restore
    - dnx test
    - ls /opt
    - ls /root/.dnx

cache:
  mount:
    - /root/.dnx