build:
  image: microsoft/aspnet:1.0.0-rc1-update1-coreclr
  commands:
    - ls
    - ls $DNX_USER_HOME
    - ls /opt
    - which dnx
    - which dnu
    - apt-get install -qqy tree
    - tree
    - dnu restore
    - dnx test

cache:
  mount:
    - /root/.dnx