build:
  image: microsoft/aspnet:1.0.0-rc1-update1-coreclr
  environment:
    - DNX_PACKAGES=nuget_cache
  commands:
    - mkdir -p nuget_cache
    - dnu restore --packages nuget_cache
    - dnx test

cache:
  mount:
    - nuget_cache
    - project.lock.json
