build:
  image: microsoft/aspnet:1.0.0-rc1-update1-coreclr
  environment:
    - DNX_PACKAGES=$PWD/nuget_cache
  commands:
    - env
    - mkdir -p nuget_cache
    - dnu restore
    - dnx test

cache:
  mount:
    - nuget_cache
    - project.lock.json
