build:
  image: microsoft/aspnet:1.0.0-rc1-update1-coreclr
  commands:
    - ls
    - ls $DNX_USER_HOME
    - ls /opt
    - which dnx
    - which dnu
    - mv nuget_cache /root/.dnx
    - rm -rf nuget_cache
    - dnu restore
    - dnx test
    - mv /root/.dnx nuget_cache
    - ls /opt
    - ls /root/.dnx

cache:
  mount:
    - nuget_cache